name: PyPi Release

on:
    push:
    pull_request:

# based on https://github.com/pypa/gh-action-pypi-publish
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Hatch
      run: pip install hatch
    - name: Build
      run: hatch build
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
